Add recreate-web target, and add/remove unneeded 'sudo'.

diff --git a/s/d-psql b/s/d-psql
--- a/s/d-psql
+++ b/s/d-psql
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-docker ps >> /dev/null
-if [ $? -eq 1 ] ; then
-  echo "If the Docker daemon *is* running — then you can try with 'sudo'?"
-  exit 1
-fi
+# docker ps >> /dev/null
+# if [ $? -eq 1 ] ; then
+#   echo "If the Docker daemon *is* running — then you can try with 'sudo'?"
+#   exit 1
+# fi
 
-up_line=`docker-compose ps rdb | egrep '\<Up\>'`
+up_line=$(sudo docker-compose ps rdb | egrep '\<Up\>')
 if [ -z "$up_line" ]; then
   echo "Error: The database Docker container 'rdb' is not running."
   echo "You can start it:"
@@ -20,5 +20,4 @@ if [ "$#" -ne 2 ]; then
   exit 1
 fi
 
-docker-compose exec rdb psql $1 $2
-
+sudo docker-compose exec rdb psql $1 $2
