Skip Webdriverio 6tests if wrong Nodejs version
I'll run the test suite twice, once with old Nodejs v14, once with v22.

diff --git a/s/wdio b/s/wdio
--- a/s/wdio
+++ b/s/wdio
@@ -1,5 +1,24 @@
 #!/bin/bash
 
+# These tests need Nodejs 14. Newer versions don't support Webdriverio's synchronous mode.
+#
+# Let's run the e2e tests first with Nodejs 22, then Nodejs 14. We'll have to return
+# exit code 0 here then, if is v22 not v14.  Otherwise (if returning 1) we'd fail
+# the test suite, or we'd need to rewrite  s/run-e2e-tests quite a lot?
+# This is simpler:   [e2e_nodejs_old_v14]
+#
+node_ver=$(node --version)
+if [[ "$node_ver" == v14.* ]]; then
+  : # Correct version — run the tests.
+elif [[ "$node_ver" == v22.* ]]; then
+  echo "Skipping this test — it needs Nodejs v14, but now we're using $node_ver."
+  exit 0
+else
+  echo "Totally unexpected Nodejs version. Is: $node_ver, should be v14 (or v22)."
+  exit 1
+fi
+
+
 cd tests/e2e/
 
 
