Add play-time e2e test setting, upgr ed-prod-one-test.

diff --git a/s/wdio-debug-9101 b/s/wdio-debug-9101
--- a/s/wdio-debug-9101
+++ b/s/wdio-debug-9101
@@ -2,3 +2,10 @@
 # To which you can connect like so: `node debug 127.0.0.1:9101`
 
 node --debug --inspect=9100 ./node_modules/webdriverio/bin/wdio $@
+exit_code=$?
+
+if [ $exit_code -ne 0 ]; then
+  echo "Error. E2E test failed, exit code: $exit_code"
+fi
+
+exit $exit_code
