Make embedded comments work again, wip.

diff --git a/s/wdio b/s/wdio
--- a/s/wdio
+++ b/s/wdio
@@ -1,1 +1,10 @@
-../node_modules/webdriverio/bin/wdio
+#!/bin/bash
+
+./node_modules/webdriverio/bin/wdio $@
+exit_code=$?
+
+if [ $exit_code -ne 0 ]; then
+  echo "Error. E2E test failed."
+fi
+
+exit $exit_code
